on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo swapoff -a
          dev="$(findmnt -T /mnt -n -o SOURCE)"
          echo "$dev"
          sudo umount /mnt
          sudo mount
          sudo findmnt
          sudo mkswap -f "$dev"
          sudo swapon "$dev"
