on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          free -h
          swap_file="$(swapon --noheadings --show=NAME)"
          echo "$swap_file"
          sudo swapoff "$swap_file"
          sudo rm "$swap_file"
          sudo truncate -s 12G "$swap_file"
          sudo swapon "$swap_file"
          free -h
